[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-dejavu",
]

[phases.install]
cmds = [
  "npm install --prefix server",
  "npm install --include=dev --prefix client",
]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
